[package]
name = "sonogram"
description = "A spectrograph utility written in Rust"
version = "0.3.0"
authors = ["Simon M. Werner <simonwerner@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
edition = "2018"
repository = "https://github.com/psiphi75/rust-sonogram"
keywords = ["spectrogram", "spectrograph", "audio", "fft", "dft"]
categories = ["multimedia::images", "science", "multimedia::audio", "visualization"]


[dependencies]
hound = "3.4.0"
num = "0.2.0"
clap = "2.33.0"
png = "0.14.0"